# secrets.toml

[credentials]

  [credentials.users]
    [credentials.users.elite]
    name = "Default User"
    email = ""
    password = "pbkdf2-sha256$29000$UqpVitFaq7X2vldqrVWKEQ$dsIpAuGG3g6ATwGgDFr6V6sId8.e.ztfbhLfz8VfIGs"  # from your hashed list

   
[cookie]
name = "edot_manager_auth"
key = "QZHc80RDo7fut47Vug3dGtsySIY39nF8"
expiry_days = 30
